# Generated by Django 3.2 on 2021-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_project_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ManyToManyField(related_name='student', to='st.Project'),
        ),
    ]
