# Generated by Django 3.2 on 2021-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0007_auto_20210930_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sername', models.CharField(max_length=64)),
                ('faculty', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=64)),
                ('program', models.CharField(max_length=64)),
                ('year', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('study_starting_time', models.TimeField()),
                ('study_end_time', models.TimeField()),
                ('project', models.ManyToManyField(blank=True, default='-', null=True, to='st.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
