# Generated by Django 3.2 on 2021-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0008_auto_20211005_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, default='-', null=True, to='st.Student'),
        ),
    ]
